grpc:
  host: "0.0.0.0"
  port: "50052"
postgres:
  host: "auth-pg"
  port: "5432"
  user: "auth-user"
  password: "auth-password"
  dbname: "auth"
  sslmode: "disable"
redis:
  host: "auth-redis"
  port: "6379"
  connection_timeout: "5s"
  max_idle: 10
  idle_timeout: "300s"