version: '3.9'

volumes:
  postgres_volume:
  redis-data:

services:
  auth:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: always
    depends_on:
      - auth-pg
    ports:
      - "50052:50052"
    environment:
      - CONFIG_PATH=/config.yaml

  auth-pg:
    image: postgres:16.3-alpine3.20
    env_file:
      - ".env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  auth-migrator:
    build:
      context: .
      dockerfile: ./build/migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: auth-pg

  auth-redis:
    image: redis:7.2.5-alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data