grpc:
  host: "0.0.0.0"
  port: "50052"
postgres:
  host: "auth-pg"
  port: "5432"
  user: "auth-user"
  password: "auth-password"
  dbname: "auth"
  sslmode: "disable"
redis:
  host: "auth-redis"
  port: "6379"
  connection_timeout: "5s"
  max_idle: 10
  idle_timeout: "300s"
http:
  host: "0.0.0.0"
  port: "8080"
  read_header_timeout: 10
swagger:
  host: "0.0.0.0"
  port: "8090"
  read_header_timeout: 10
kafka_consumer:
  user_creation_topic_name: "User-Creation"
  brokers: "localhost:9092, localhost:9093, localhost:9094"
  group_id: "User"